version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: sasol-attendance-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - sasol-network

  backend:
    build: ./backend
    container_name: sasol-attendance-api
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_SERVICE: ${EMAIL_SERVICE}
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - sasol-network
    volumes:
      - ./backend/uploads:/usr/src/app/uploads

  frontend:
    build: ./frontend
    container_name: sasol-attendance-ui
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - sasol-network

networks:
  sasol-network:
    driver: bridge

volumes:
  postgres_data:
